[package]
name = "planetarium"
version = "0.1.0"
edition = "2021"
resolver = "2"

[dependencies]
bevy = { version = "0.10", features = ["bevy_asset", "bevy_render"] }
uuid = { version = "1.3", features = ["v4"] }
rand = "0.8"
byteorder = "1.4"
chrono = "0.4.41"
meshtext   = "0.3.1"      # â† for runtime 3D text mesh generation
